### ISSUE TITLE
Does it generalize to unseen in-the-wild point clouds? 

### ISSUE THREAD

**Issue by coreqode** [rabbityl/lepard#1]
Hi, this is amazing work. 
Does the pre-trained model generalise to in-the-wild point clouds? or it is specific to trained datasets only?

**Comment by rabbityl** [comment]
It generalizes well to real-world kinect style scanner based point clouds.

**Comment by coreqode** [comment]
Is there any codebase for testing the pre-trained models in in-the-wild scenarios?

**Comment by rabbityl** [comment]
This can be achieved by changing the dataset using your custom sensor data.

**Comment by Guptajakala** [comment]
@rabbityl when I applied to my own data, I got flow all zeros. R and t are identity and zeros. The confidence matrix has all very small values. What could be the problem?
