### ISSUE TITLE
in dataloader.py line 5 ,import cpp_wrappers.cpp_neighbors.radius_neighbors as cpp_neighbors

### ISSUE THREAD

**Issue by WuHaoYu21** [rabbityl/lepard#11]
in dataloader.py line 5 , ' import cpp_wrappers.cpp_neighbors.radius_neighbors as cpp_neighbors '
sorry, i don't find ''radius_neighbors'' in file: cpp_wrappers/cpp_neighbors.
i want to know how to solve this problem.
thank you.

**Comment by rabbityl** [comment]
It's a C++ extension need to be installed first
`cd cpp_wrappers; sh compile_wrappers.sh; cd ..`
