### ISSUE TITLE
when i trained using 3dmatch , the dataloader have one problem

### ISSUE THREAD

**Issue by WuHaoYu21** [rabbityl/lepard#13]
in main.py line 99 ,'cofig.train_loader, neighborhood_limits = get_dataloader(train_set,config,shuffle=True)'
this line have one problem.
the 'train_set' need one file '3dmatch/3dmatch/train/rgbd-scenes-v2-scene_01/cloud_bin_1.pth' , but i can't find the ''cloud_bin_1.pth''.
i have already download 3dmatch.zip ,and unzip this file.
but in the unzip file,i don't find the ''cloud_bin_1.pth''.
i hope you can help me.
thank you very much.

**Comment by 35p32** [comment]
Please  post the error log

**Comment by zihui6389** [comment]
I have encountered the same problem. 

This is the error log:
`(Lepard) G:\lepard>python main.py configs/test/3dmatch.yaml
Traceback (most recent call last):
  File "main.py", line 99, in <module>
    config.train_loader, neighborhood_limits = get_dataloader(train_set,config,shuffle=True)
  File "G:\lepard\datasets\dataloader.py", line 622, in get_dataloader
    neighborhood_limits = calibrate_neighbors(dataset, config['kpfcn_config'], collate_fn=collate_fn)
  File "G:\lepard\datasets\dataloader.py", line 571, in calibrate_neighbors
    batched_input = collate_fn([dataset[i]], config, neighborhood_limits=[hist_n] * 5)
  File "G:\lepard\datasets\_3dmatch.py", line 67, in __getitem__
    src_pcd = torch.load(src_path)
  File "E:\Anaconda3\envs\Lepard\lib\site-packages\torch\serialization.py", line 579, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "E:\Anaconda3\envs\Lepard\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "E:\Anaconda3\envs\Lepard\lib\site-packages\torch\serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'data/3dmatch\\train/rgbd-scenes-v2-scene_01/cloud_bin_1.pth'`

**Comment by WuHaoYu21** [comment]
> 

yes.
Maybe the dataset:3dmatch.zip has been already changed?
So, we can't find the ****.pth ?
i don't know.

**Comment by WuHaoYu21** [comment]
> I have encountered the same problem.
> 
> This is the error log:
> 
> ```
> (Lepard) G:\lepard>python main.py configs/test/3dmatch.yaml
> Traceback (most recent call last):
>   File "main.py", line 99, in <module>
>     config.train_loader, neighborhood_limits = get_dataloader(train_set,config,shuffle=True)
>   File "G:\lepard\datasets\dataloader.py", line 622, in get_dataloader
>     neighborhood_limits = calibrate_neighbors(dataset, config['kpfcn_config'], collate_fn=collate_fn)
>   File "G:\lepard\datasets\dataloader.py", line 571, in calibrate_neighbors
>     batched_input = collate_fn([dataset[i]], config, neighborhood_limits=[hist_n] * 5)
>   File "G:\lepard\datasets\_3dmatch.py", line 67, in __getitem__
>     src_pcd = torch.load(src_path)
>   File "E:\Anaconda3\envs\Lepard\lib\site-packages\torch\serialization.py", line 579, in load
>     with _open_file_like(f, 'rb') as opened_file:
>   File "E:\Anaconda3\envs\Lepard\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
>     return _open_file(name_or_buffer, mode)
>   File "E:\Anaconda3\envs\Lepard\lib\site-packages\torch\serialization.py", line 211, in __init__
>     super(_open_file, self).__init__(open(name, mode))
> FileNotFoundError: [Errno 2] No such file or directory: 'data/3dmatch\\train/rgbd-scenes-v2-scene_01/cloud_bin_1.pth'
> ```

Thise

> I have encountered the same problem.
> 
> This is the error log:
> 
> ```
> (Lepard) G:\lepard>python main.py configs/test/3dmatch.yaml
> Traceback (most recent call last):
>   File "main.py", line 99, in <module>
>     config.train_loader, neighborhood_limits = get_dataloader(train_set,config,shuffle=True)
>   File "G:\lepard\datasets\dataloader.py", line 622, in get_dataloader
>     neighborhood_limits = calibrate_neighbors(dataset, config['kpfcn_config'], collate_fn=collate_fn)
>   File "G:\lepard\datasets\dataloader.py", line 571, in calibrate_neighbors
>     batched_input = collate_fn([dataset[i]], config, neighborhood_limits=[hist_n] * 5)
>   File "G:\lepard\datasets\_3dmatch.py", line 67, in __getitem__
>     src_pcd = torch.load(src_path)
>   File "E:\Anaconda3\envs\Lepard\lib\site-packages\torch\serialization.py", line 579, in load
>     with _open_file_like(f, 'rb') as opened_file:
>   File "E:\Anaconda3\envs\Lepard\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
>     return _open_file(name_or_buffer, mode)
>   File "E:\Anaconda3\envs\Lepard\lib\site-packages\torch\serialization.py", line 211, in __init__
>     super(_open_file, self).__init__(open(name, mode))
> FileNotFoundError: [Errno 2] No such file or directory: 'data/3dmatch\\train/rgbd-scenes-v2-scene_01/cloud_bin_1.pth'
> ```

i know how to solve this problem.
The dataset , you need to download from https://github.com/overlappredator/OverlapPredator

**Comment by littlewater3** [comment]
The dataset I downloaded from the link you provided is the same as the dataset provided by the author of this paper. Can we add qq friends to chat with each other.
844787024
Thanks

**Comment by littlewater3** [comment]
> in main.py line 99 ,'cofig.train_loader, neighborhood_limits = get_dataloader(train_set,config,shuffle=True)' this line have one problem. the 'train_set' need one file '3dmatch/3dmatch/train/rgbd-scenes-v2-scene_01/cloud_bin_1.pth' , but i can't find the ''cloud_bin_1.pth''. i have already download 3dmatch.zip ,and unzip this file. but in the unzip file,i don't find the ''cloud_bin_1.pth''. i hope you can help me. thank you very much.

Hi, I have some questions about Lepard debugging.
dataset/dataloader.py  line 5
I can't find the file for cpp_wrappers.cpp_neighbors. Radius_neighbors
Can we add QQ friends to chat each other
QQ number: 844787024

**Comment by qsisi** [comment]
> 

```
cd cpp_wrappers
sh compile_wrappers.sh
cd ..
```

**Comment by qsisi** [comment]
> > in main.py line 99 ,'cofig.train_loader, neighborhood_limits = get_dataloader(train_set,config,shuffle=True)' this line have one problem. the 'train_set' need one file '3dmatch/3dmatch/train/rgbd-scenes-v2-scene_01/cloud_bin_1.pth' , but i can't find the ''cloud_bin_1.pth''. i have already download 3dmatch.zip ,and unzip this file. but in the unzip file,i don't find the ''cloud_bin_1.pth''. i hope you can help me. thank you very much.
> 
> Hi, I have some questions about Lepard debugging. dataset/dataloader.py line 5 I can't find the file for cpp_wrappers.cpp_neighbors. Radius_neighbors Can we add QQ friends to chat each other QQ number: 844787024

```
cd cpp_wrappers
sh compile_wrappers.sh
cd ..
```

**Comment by WuHaoYu21** [comment]
> 

i can't find your qq number

**Comment by littlewater3** [comment]
> > 
> 
> 我找不到你的qq号码

QQ number ：844787024
or Wechat number：18251306780
Thanks

**Comment by littlewater3** [comment]
> > > 在 main.py 第 99 行，'cofig.train_loader,neighborhood_limits = get_dataloader(train_set,config,shuffle=True)' 这一行有一个问题。“train_set”需要一个文件“3dmatch/3dmatch/train/rgbd-scenes-v2-scene_01/cloud_bin_1.pth”，但我找不到“cloud_bin_1.pth”。我已经下载了 3dmatch.zip 并解压这个文件。但在解压缩文件中，我没有找到“cloud_bin_1.pth”。我希望你能帮助我。非常感谢您。
> > 
> > 
> > 嗨，我有一些关于 Lepard 调试的问题。dataset/dataloader.py 第 5 行我找不到 cpp_wrappers.cpp_neighbors 的文件。Radius_neighbors 可以加QQ好友互相聊天吗QQ号：844787024
> 
> ```
> cd cpp_wrappers
> sh compile_wrappers.sh
> cd ..
> ```

thanks

**Comment by ChaunceyQ** [comment]
I also have the same problem, may I ask how to solve it at last？？？

**Comment by ChaunceyQ** [comment]
> > I have encountered the same problem.
> > This is the error log:
> > ```
> > (Lepard) G:\lepard>python main.py configs/test/3dmatch.yaml
> > Traceback (most recent call last):
> >   File "main.py", line 99, in <module>
> >     config.train_loader, neighborhood_limits = get_dataloader(train_set,config,shuffle=True)
> >   File "G:\lepard\datasets\dataloader.py", line 622, in get_dataloader
> >     neighborhood_limits = calibrate_neighbors(dataset, config['kpfcn_config'], collate_fn=collate_fn)
> >   File "G:\lepard\datasets\dataloader.py", line 571, in calibrate_neighbors
> >     batched_input = collate_fn([dataset[i]], config, neighborhood_limits=[hist_n] * 5)
> >   File "G:\lepard\datasets\_3dmatch.py", line 67, in __getitem__
> >     src_pcd = torch.load(src_path)
> >   File "E:\Anaconda3\envs\Lepard\lib\site-packages\torch\serialization.py", line 579, in load
> >     with _open_file_like(f, 'rb') as opened_file:
> >   File "E:\Anaconda3\envs\Lepard\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
> >     return _open_file(name_or_buffer, mode)
> >   File "E:\Anaconda3\envs\Lepard\lib\site-packages\torch\serialization.py", line 211, in __init__
> >     super(_open_file, self).__init__(open(name, mode))
> > FileNotFoundError: [Errno 2] No such file or directory: 'data/3dmatch\\train/rgbd-scenes-v2-scene_01/cloud_bin_1.pth'
> > ```
> 
> i know how to solve this problem. The dataset , you need to download from https://github.com/overlappredator/OverlapPredator

I still have the same problem after downloading it，I don't know how to solve it.

**Comment by Yang-L1** [comment]
I also upload the 3DMatch to google drive. Have a try.
https://drive.google.com/file/d/14gwrAdk8CPlm1SszUYu4w7oMqgx6Nyqa/view?usp=sharing
