### ISSUE TITLE
Questions about the implementation of soft procrustes 

### ISSUE THREAD

**Issue by qsisi** [rabbityl/lepard#16]
How to understand the **condition** number during SVD decomposition?

**Comment by rabbityl** [comment]
It shows if the problem is ill-posed. We basically ignore results of the SVD if the problem is ill-posed (i.e. with large condition number). This stablize the early training phase.

**Comment by qsisi** [comment]
Yes, thanks for your reply, and I know that the **condition number** is set to check whether the results of the SVD are valid, but may I ask what is the actual meaning of the computed **condition number**? Could you give some hints about it? 

Thanks very much for your help.

**Comment by rabbityl** [comment]
Maybe check this https://zhuanlan.zhihu.com/p/91393594

**Comment by qsisi** [comment]
Thanks for your reply.
