### ISSUE TITLE
Some question about the paper

### ISSUE THREAD

**Issue by Gilgamesh666666** [rabbityl/lepard#2]
Hi,

Thank you for sharing your excellent work! I have read the paper recently, and I have some questions about the position encoding. In your paper, you add position encoding to three places: self-attention, cross-attention, confidence matrix. And as you mention in the paper, position encoding in cross-attention and matching may mislead the registration at the beginning. So, I wonder if you have compared the performance at the situation you remove the position encoding at the cross-attention part and the confidence matrix part at the first stage but retain them at the second stage. Plus, I think the figures in your paper are very beautiful. So could you please tell me how you draw the point cloud and correspondences of figure 7 in your paper and the point cloud video in the readme? I will be very appreciative if you can give me some hints about the above question. Thank you very much!

**Comment by rabbityl** [comment]
We did not check what happens if remove them, but agree it worth trying. For the drawing, we transfer all points/lines to meshes and render them with blender's cycle engine.

**Comment by 35p32** [comment]
> ntion part and the confidence matrix part at the first stage but retain them at the second stage. Plus, I think the figures in your paper are very beautiful. So could you please tell me how you draw the point cloud and correspondences of figure 7 in your paper and the point cloud video in the readme? I will be very appreciative if you can give me some hints about the above qu

Sir, It is an excellent idea !  Did you do this experiment?  will the result increase or decrease?

**Comment by Gilgamesh666666** [comment]
> > ntion part and the confidence matrix part at the first stage but retain them at the second stage. Plus, I think the figures in your paper are very beautiful. So could you please tell me how you draw the point cloud and correspondences of figure 7 in your paper and the point cloud video in the readme? I will be very appreciative if you can give me some hints about the above qu
> 
> Sir, It is an excellent idea ! Did you do this experiment? will the result increase or decrease?

Sorry, I didn't. I am a little busy these days :(
