### ISSUE TITLE
Error while executing sh compile_wrappers.sh for installing C++ extension

### ISSUE THREAD

**Issue by mnrmja007** [rabbityl/lepard#20]
Hi

I am trying to bring up lepard but I am facing issues while installing C++ extension. Logs are attached below

My system specifications
1. Windows 11
2. using WSL (subsystem for Linux on windows)

Can you please provide some input for solving this?

`running build_ext
building 'grid_subsampling' extension
Warning: Can't read registry to find the necessary compiler setting
Make sure that Python modules winreg, win32api or win32con are installed.
C compiler: gcc -pthread -B /home/grblr06/anaconda3/envs/lepard/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC

compile options: '-I/home/grblr06/anaconda3/envs/lepard/lib/python3.8/site-packages/numpy/core/include -I/home/grblr06/anaconda3/envs/lepard/include/python3.8 -c'
extra options: '-std=c++11 -D_GLIBCXX_USE_CXX11_ABI=0'
gcc: ../cpp_utils/cloud/cloud.cpp
gcc: wrapper.cpp
gcc: grid_subsampling/grid_subsampling.cpp
error: Command "gcc -pthread -B /home/grblr06/anaconda3/envs/lepard/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/grblr06/anaconda3/envs/lepard/lib/python3.8/site-packages/numpy/core/include -I/home/grblr06/anaconda3/envs/lepard/include/python3.8 -c grid_subsampling/grid_subsampling.cpp -o build/temp.linux-x86_64-3.8/grid_subsampling/grid_subsampling.o -std=c++11 -D_GLIBCXX_USE_CXX11_ABI=0" failed with exit status 127
running build_ext
building 'radius_neighbors' extension
Warning: Can't read registry to find the necessary compiler setting
Make sure that Python modules winreg, win32api or win32con are installed.
C compiler: gcc -pthread -B /home/grblr06/anaconda3/envs/lepard/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC

compile options: '-I/home/grblr06/anaconda3/envs/lepard/lib/python3.8/site-packages/numpy/core/include -I/home/grblr06/anaconda3/envs/lepard/include/python3.8 -c'
extra options: '-std=c++11 -D_GLIBCXX_USE_CXX11_ABI=0'
gcc: ../cpp_utils/cloud/cloud.cpp
gcc: wrapper.cpp
gcc: neighbors/neighbors.cpp
error: Command "gcc -pthread -B /home/grblr06/anaconda3/envs/lepard/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/grblr06/anaconda3/envs/lepard/lib/python3.8/site-packages/numpy/core/include -I/home/grblr06/anaconda3/envs/lepard/include/python3.8 -c neighbors/neighbors.cpp -o build/temp.linux-x86_64-3.8/neighbors/neighbors.o -std=c++11 -D_GLIBCXX_USE_CXX11_ABI=0" failed with exit status 127`

**Comment by rabbityl** [comment]
The extension is borrowed from [KPConv](https://github.com/HuguesTHOMAS/KPConv-PyTorch).
You can refer to the windows installation instructions [here](https://github.com/HuguesTHOMAS/KPConv-PyTorch/blob/master/INSTALL.md).

**Comment by mnrmja007** [comment]
@rabbityl I was able to build C++ extension in Anaconda on windows

Now while running the evaluation script I get the below error. Can you please provide some pointers for solving this?

```
> Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from datasets.dataloader import get_dataloader, get_datasets
  File "C:\Users\Gridraster\Documents\GitHub\lepard\datasets\dataloader.py", line 5, in <module>
    import cpp_wrappers.cpp_neighbors.radius_neighbors as cpp_neighbors
ModuleNotFoundError: No module named 'cpp_wrappers.cpp_neighbors.radius_neighbors'
```
