### ISSUE TITLE
Licence missing in this repo

### ISSUE THREAD

**Issue by mnrmja007** [rabbityl/lepard#23]
Hi @rabbityl 

Can you please add the license to this repo? This will help us understand if we can use this for commercial use or not

Thanks!

**Comment by AtsushiHashimoto** [comment]
Hi @rabbityl . Thank you for your great work. I would also like to request you to clarify the license.
Thanks in advance!

**Comment by rabbityl** [comment]
Done.

**Comment by AtsushiHashimoto** [comment]
Thank you for your quick response!
