### ISSUE TITLE
how can I test a sinlge pcd file?

### ISSUE THREAD

**Issue by LLsmile** [rabbityl/lepard#4]
how can I test a sinlge pcd file?

**Comment by rabbityl** [comment]
The simplest way is to modify input data in the [lib/tester.py](https://github.com/rabbityl/lepard/blob/main/lib/tester.py) with your pcd data.  We will also add demo code later.

**Comment by ttsesm** [comment]
@rabbityl, I am also interested to test with some custom pcds. Can you possibly give some more info how to call the tester.py with my pcd data or whether you have any demo code already implemented.

Thanks.

**Comment by recordmp3** [comment]
@rabbityl Do you have any demo code for this which you said you would add? Thank you in advance!
