### ISSUE TITLE
Non-rigid ICP implementation.

### ISSUE THREAD

**Issue by ghost** [rabbityl/lepard#7]
Hello, I notice that N-ICP is used for deformable registration in the paper. How can I find the N-ICP implementation? Thank you.

**Comment by rabbityl** [comment]
We will release our N-ICP implementation before the conference. This [repo](https://github.com/Juyong/Fast_RNRR) might also be helpful.

**Comment by qinzheng93** [comment]
Looking forward to it. Thanks a lot.
